spring:
  application:
    name: demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password:
    hikari:
      poolName: Hikari
      auto-commit: false